### ISSUE TITLE
Where can i get the Rainbowduino v3.0 Board?

### ISSUE THREAD

**Issue by kdenzel** [unwiredben/Rainbowduino-v3#1]
I built the Rainbow cube kit, but forgot to buy a Rainbowduino. Now i am stuck with my Arduino Uno and have no idea, how to communicate with this thing without the Rainbowduino. oO

**Comment by unwiredben** [comment]
Sorry, I don't know of any stock anywhere.  I don't work for Seeed, I just preserved their library code here.
